import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../providers/cart_provider.dart';
import '../../providers/auth_provider.dart';
import '../../providers/order_provider.dart';
import '../../services/payment_service.dart';
import '../../models/order_model.dart';
import '../../core/constants.dart';

class CheckoutScreen extends ConsumerStatefulWidget {
  const CheckoutScreen({super.key});

  @override
  ConsumerState<CheckoutScreen> createState() => _CheckoutScreenState();
}

class _CheckoutScreenState extends ConsumerState<CheckoutScreen> {
  bool _isProcessing = false;
  final _paymentService = PaymentService();

  void _handlePayment() async {
    final cartItems = ref.read(cartProvider);
    final cartNotifier = ref.read(cartProvider.notifier);
    final user = ref.read(userModelProvider).value;
    final authUser = ref.read(authStateProvider).value;

    if (authUser == null) {
      context.push('/login');
      return;
    }

    setState(() => _isProcessing = true);

    try {
      // 1. Trigger Payment
      final success = await _paymentService.makePayment(cartNotifier.total, 'usd');

      if (success) {
        // 2. Create Order in Firestore
        final order = OrderModel(
          id: '', // Generated by Firestore
          buyerId: authUser.uid,
          sellerId: cartItems[0].product.sellerId,
          items: cartItems.map((e) => e.toOrderItem()).toList(),
          total: cartNotifier.total,
          status: OrderStatus.pending,
          createdAt: DateTime.now(),
          stripePaymentIntentId: 'mock_pi_${DateTime.now().millisecondsSinceEpoch}',
        );

        await ref.read(orderProvider).createOrder(order);

        // 3. Clear Cart and Navigate to Success
        ref.read(cartProvider.notifier).clearCart(); // Explicitly use ref.read
        
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Payment Successful! Order placed.')),
          );
          context.go('/');
        }
      } else {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Payment cancelled or failed.')),
          );
        }
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _isProcessing = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final cartItems = ref.watch(cartProvider);
    final cartNotifier = ref.read(cartProvider.notifier);

    return Scaffold(
      appBar: AppBar(title: const Text('Checkout')),
      body: Column(
        children: [
          Expanded(
            child: ListView(
              padding: const EdgeInsets.all(24),
              children: [
                const Text('Order Summary', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
                const SizedBox(height: 16),
                ...cartItems.map((item) => Padding(
                      padding: const EdgeInsets.only(bottom: 12),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Expanded(
                            child: Text(
                              '${item.quantity}x ${item.product.name}',
                              overflow: TextOverflow.ellipsis,
                            ),
                          ),
                          const SizedBox(width: 16),
                          Text('\$${(item.product.price * item.quantity).toStringAsFixed(2)}'),
                        ],
                      ),
                    )),
                const Divider(height: 32),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const Text('Total', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
                    Text(
                      '\$${cartNotifier.total.toStringAsFixed(2)}',
                      style: const TextStyle(fontSize: 22, fontWeight: FontWeight.bold, color: AppColors.primary),
                    ),
                  ],
                ),
              ],
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(24.0),
            child: _isProcessing
                ? const Center(child: CircularProgressIndicator())
                : FilledButton(
                    onPressed: _handlePayment,
                    child: const Text('Pay Now'),
                  ),
          ),
        ],
      ),
    );
  }
}
